baseURL = "https://blog.truggeri.com/"
languageCode = "en-us"
theme = "PaperMod"
title = "TRuggeri Blog"

[params]
  defaultTheme = "dark"
  disableThemeToggle = true

[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
  weight = 20

[markup.goldmark.renderer]
  unsafe = true